name = "SliceSamplingProject"
uuid = "0e68a3f3-cd0a-482b-8be1-53867758a12f"
authors = ["Annegret Pohle <apohle@ethz.ch>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
